steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - CloudBuildFunction
  - --source=.
  - --trigger-http
  - --runtime=dotnet6
options:
  logging: CLOUD_LOGGING_ONLY