steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - HelloWorld.Function
  - --region=europe-west1
  - --source=ProductivityTools.Journal.ImageProvider
  - --trigger-http
  - --runtime=dotnet6
options:
  logging: CLOUD_LOGGING_ONLY